import { ArrowRight, FileText } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";

import { PageHeader, Section } from "@/components/layout/page-header";
import { Markdown } from "@/components/methods/markdown";
import { ScrollRegion } from "@/components/stats/scroll-table";
import benchmark from "@/lib/data/agent-benchmark.json";
import { listDecisions, readDoc, withoutTitle } from "@/lib/content/docs";
import {
  loadAlphaBetaStudy,
  loadAstarStudy,
  loadPythonCrosscheck,
  loadReferenceTournament,
} from "@/lib/data/load";
import { SITE } from "@/lib/site";

export const metadata: Metadata = {
  title: "Methods & decisions",
  description:
    "Data provenance, methods, evaluation design, assumptions and limitations behind every number on Cachex Arena, plus decision records, the agent card and the AI use statement.",
};

export default function MethodsPage() {
  const decisions = listDecisions();
  const ref = loadReferenceTournament().meta;
  const astar = loadAstarStudy().meta;
  const ab = loadAlphaBetaStudy().meta;
  const py = loadPythonCrosscheck().meta;
  const provenance = [
    {
      what: "Original benchmark: agent vs random, 160 games",
      how: "Original Python, unchanged, via the subject's referee",
      source: benchmark.meta.generatedBy,
      detail: `Python ${benchmark.meta.python}, PYTHONHASHSEED=${benchmark.meta.pythonHashSeed}`,
    },
    {
      what: "Parity fixtures (A*, rules, evaluation, minimax, moves)",
      how: "Original Python, unchanged; shuffle replaced by a sort and bias fixed at 1",
      source: "scripts/generate_parity_fixtures.py",
      detail: "CPython 3.12",
    },
    {
      what: "Reference round robin, 1,200 games",
      how: ref.implementation,
      source: ref.generatedBy,
      detail: `seed ${String(ref.config.seed)}; ${ref.cpu}; Node ${ref.node}; ${ref.generatedAt}`,
    },
    {
      what: "Python cross-check, 480 games",
      how: py.implementation,
      source: py.generatedBy,
      detail: `Python ${py.python}, PYTHONHASHSEED=0; seed ${String(py.config.seed)}`,
    },
    {
      what: "A* paired heuristic study, 980 boards",
      how: astar.implementation,
      source: astar.generatedBy,
      detail: `seed ${String(astar.config.seed)}; the notebook's board generator`,
    },
    {
      what: "Alpha-beta efficiency, 480 searches",
      how: ab.implementation,
      source: ab.generatedBy,
      detail: `seed ${String(ab.config.seed)}; positions from greedy-vs-random games`,
    },
  ];

  return (
    <div className="table-felt">
      <div className="mx-auto max-w-7xl space-y-10 px-4 py-6 sm:px-6 lg:py-10">
        <PageHeader eyebrow="Methods" title="How every number on this site was made">
          <p>
            Provenance, methods and evaluation design for the tournament, the A* study and the
            alpha-beta study; the assumptions and limitations behind them; and the decisions, agent
            card and AI use statement that go with them.
          </p>
          <nav aria-label="On this page" className="flex flex-wrap gap-x-3 gap-y-1 text-sm">
            {[
              ["#provenance", "Data provenance"],
              ["#method", "Method"],
              ["#evaluation", "Evaluation design"],
              ["#assumptions", "Assumptions and limitations"],
              ["#change", "What I'd change"],
              ["#decisions", "Decision records"],
              ["#ai-use", "AI use statement"],
            ].map(([href, label]) => (
              <a key={href} href={href} className="underline underline-offset-4">
                {label}
              </a>
            ))}
          </nav>
        </PageHeader>

        <Section id="provenance" eyebrow="Where the data comes from" title="Data provenance">
          <p className="text-muted-foreground max-w-3xl text-sm">
            There is no external dataset. Every result is generated by running code in this
            repository with a fixed seed, and the generating script is named next to it. The
            original 2022 Python in <code className="font-mono">coursework/</code> is never
            modified; the TypeScript port is checked against it by parity tests (DR-003).
          </p>
          <ScrollRegion label="Data provenance table" className="mt-4">
            <table className="w-full min-w-[720px] text-sm">
              <thead className="text-muted-foreground text-left text-xs">
                <tr className="border-b">
                  <th scope="col" className="py-2 pr-3 font-medium">
                    Artefact
                  </th>
                  <th scope="col" className="py-2 pr-3 font-medium">
                    Produced by
                  </th>
                  <th scope="col" className="py-2 pr-3 font-medium">
                    Script
                  </th>
                  <th scope="col" className="py-2 font-medium">
                    Run details
                  </th>
                </tr>
              </thead>
              <tbody>
                {provenance.map((p) => (
                  <tr key={p.what} className="border-border/50 border-b align-top last:border-0">
                    <th scope="row" className="py-2 pr-3 text-left font-medium">
                      {p.what}
                    </th>
                    <td className="text-muted-foreground py-2 pr-3">{p.how}</td>
                    <td className="py-2 pr-3">
                      <a
                        href={`${SITE.repo}/blob/${SITE.ref}/${p.source}`}
                        target="_blank"
                        rel="noreferrer"
                        className="font-mono text-xs underline underline-offset-4"
                      >
                        {p.source}
                      </a>
                    </td>
                    <td className="text-muted-foreground py-2 font-mono text-xs">{p.detail}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </ScrollRegion>
        </Section>

        <Section id="method" eyebrow="What was done" title="Method">
          <div className="grid gap-6 lg:grid-cols-3">
            <Block title="Agents and variants">
              The original agent plus variants that each change one knob: depth fixed at 2 or 3, and
              greedy one-ply (depth 1, no opening book). The same variants are rebuilt from the
              unchanged Python for the cross-check by patching{" "}
              <code className="font-mono text-xs">dynamic_depth_allocation</code> and the
              opening-book flag. Random is the subject&apos;s baseline.
            </Block>
            <Block title="Round robin">
              Every pairing plays the same number of games on each board size, as colour-swapped
              pairs: one seed, played twice with the agents swapping Red and Blue, so the first-move
              effect cancels within a pairing. The referee port validates every move; an illegal
              move or crash forfeits the game. Per-move seeds are derived from the game seed and
              move number, so any game can be replayed.
            </Block>
            <Block title="Strength and uncertainty">
              Win rates: Wilson score intervals. Strengths: Bradley-Terry fitted by the MM algorithm
              (draws count half, one virtual draw per pairing to keep estimates finite), reported on
              the Elo scale with random fixed at 0, and percentile intervals from a bootstrap that
              resamples games within each pairing and board size. Move times: bootstrap intervals
              over per-game means.
            </Block>
            <Block title="A* heuristic study">
              Paired design: both heuristics search the same random boards from the notebook&apos;s
              generator, and the unit of analysis is the board. Mean per-board difference with a
              paired bootstrap interval, a Wilcoxon signed-rank test (zero differences dropped,
              tie-corrected normal approximation), the matched-pairs rank-biserial correlation and
              Cohen&apos;s d_z. Optimality is checked against breadth-first search on the same
              board.
            </Block>
            <Block title="Alpha-beta study">
              The same position is searched at the same depth and move order three ways: plain
              minimax, the original alpha-beta, and a textbook alpha-beta. The pruning ratio is the
              share of the full tree visited, with bootstrap intervals over positions. Every search
              is also checked to return the same root value as plain minimax.
            </Block>
            <Block title="Statistical code">
              All helpers live in <code className="font-mono text-xs">web/src/lib/stats</code> with
              unit tests against reference values from scipy 1.17, statsmodels and R (Wilson
              intervals, Newcombe differences, Wilcoxon exact and approximate p-values, type-7
              quantiles, Bradley-Terry maximum likelihood). Every interval shown records its seed
              and number of resamples.
            </Block>
          </div>
        </Section>

        <Section id="evaluation" eyebrow="What counts as evidence" title="Evaluation design">
          <ul className="text-foreground/90 max-w-3xl list-disc space-y-2 pl-5">
            <li>
              <strong>Questions asked:</strong> how strong is the original relative to controlled
              variants and a baseline; does dynamic depth help; does the A* heuristic choice trade
              speed for optimality; how much work does pruning save; and (with your own key) how
              does a language model compare to the random and greedy agents on identical seeds.
            </li>
            <li>
              <strong>Sample sizes are stated with every result.</strong> The reference round robin
              has 40 games per pairing per board size (120 per pairing overall), which resolves
              differences of roughly 15 to 20 percentage points in a head-to-head win rate; smaller
              differences are reported as not detectable rather than as ties.
            </li>
            <li>
              <strong>Paired comparisons where two methods are compared:</strong> heuristics on the
              same boards (paired bootstrap and Wilcoxon for node counts, paired bootstrap and exact
              McNemar for shortest-path rates), search variants on the same positions,
              colour-swapped game pairs on the same seeds, agents compared through Elo differences
              taken from the same bootstrap refits (never by whether two intervals overlap), and LLM
              versus each baseline on exactly the games the model finished (games won by only one of
              them, with an exact McNemar test).
            </li>
            <li>
              <strong>LLM answers are scored per turn, one rule for both providers:</strong> the
              rate reported is the share of turns whose first answer was rejected, split into
              illegal moves and replies with no usable move (malformed, cut off or refused), because
              retries on the same turn are not independent trials. Turns within a game are not
              independent either (same model, prompt and position history), so the Wilson interval
              is on the effective number of turns after a design effect estimated from how much the
              rate varies between games, never below 1 (DR-005). With a handful of games the design
              effect is itself rough.
            </li>
            <li>
              <strong>Effect sizes, not just p-values:</strong> differences in win rate and Elo with
              intervals, mean node differences, rank-biserial r and d_z.
            </li>
            <li>
              <strong>No self-scored metrics.</strong> Results are measured against the referee and
              against other agents, never against a score the author chose.
            </li>
            <li>
              <strong>Multiple comparisons:</strong> ten pairings are reported side by side without
              correction. Each interval is valid on its own; reading the table as a whole, expect
              about one in twenty 95% intervals to miss.
            </li>
          </ul>
        </Section>

        <Section
          id="assumptions"
          eyebrow="Read before you quote a number"
          title="Assumptions and limitations"
        >
          <div className="grid gap-6 lg:grid-cols-2">
            <Block title="Assumptions">
              <ul className="list-disc space-y-1.5 pl-5">
                <li>
                  Games are independent given their seeds; colour-swapped pairs share a seed by
                  design, and the bootstrap resamples games, not pairs.
                </li>
                <li>
                  Bradley-Terry assumes strength is one number per agent (transitive, no style
                  matchups) and pools board sizes in the &ldquo;all sizes&rdquo; view.
                </li>
                <li>
                  The TypeScript port behaves like the original in random play as well as in the
                  deterministic cases the parity tests cover; the Python cross-check supports this
                  within its resolution.
                </li>
              </ul>
            </Block>
            <Block title="Limitations">
              <ul className="list-disc space-y-1.5 pl-5">
                <li>
                  Board sizes 4 to 6 only for the round robin; the original supports up to 15 × 15,
                  where depth 1 is likely to be weaker still.
                </li>
                <li>Move times depend on hardware and are only comparable within one run.</li>
                <li>
                  The Python cross-check has 80 games per pairing and can only detect large
                  discrepancies (about ±15 points).
                </li>
                <li>
                  The A* study uses the notebook&apos;s random boards (barriers at random, up to
                  half the board); other board distributions may behave differently.
                </li>
                <li>
                  LLM-as-a-player runs are a handful of games against one opponent, with one prompt;
                  intervals are wide by design.
                </li>
              </ul>
            </Block>
          </div>
        </Section>

        <Section id="change" eyebrow="Looking back" title="What I'd change">
          <ul className="text-foreground/90 max-w-3xl list-disc space-y-2 pl-5">
            <li>
              Fix the one-line beta update and replace ratio-based depth with iterative deepening
              under a time budget, then test the change as a new variant against the original
              (DR-002).
            </li>
            <li>
              Add a connection-distance feature and tune weights against data, not by hand (DR-001).
            </li>
            <li>
              Pre-register comparisons and sample sizes before running the next tournament, and
              extend it to larger boards.
            </li>
            <li>
              Record the original Python&apos;s random draws so whole random games can be compared
              move for move across languages (DR-003).
            </li>
          </ul>
        </Section>

        <Section
          id="decisions"
          eyebrow="Decision records"
          title="Decisions, as made and as measured"
        >
          <p className="text-muted-foreground max-w-3xl text-sm">
            Each record states the decision first, then context, options, reasons, what happened
            (weak numbers included) and what I would change. Records are never edited after the
            fact; a new record supersedes an old one.
          </p>
          <ul className="mt-4 grid gap-3 md:grid-cols-3">
            {decisions.map((d) => (
              <li key={d.slug}>
                <Link
                  href={`/methods/decisions/${d.slug}`}
                  className="bg-background/50 hover:bg-muted/60 flex h-full flex-col rounded-2xl border p-4 transition-colors"
                >
                  <span className="text-muted-foreground font-mono text-xs">{d.id}</span>
                  <span className="mt-1 font-medium">{d.title}</span>
                  <span className="text-muted-foreground mt-auto flex items-center gap-1 pt-3 text-xs">
                    Read <ArrowRight className="size-3" />
                  </span>
                </Link>
              </li>
            ))}
            <li>
              <Link
                href="/methods/agent-card"
                className="bg-background/50 hover:bg-muted/60 flex h-full flex-col rounded-2xl border p-4 transition-colors"
              >
                <span className="text-muted-foreground flex items-center gap-1 text-xs">
                  <FileText className="size-3" /> Agent card
                </span>
                <span className="mt-1 font-medium">
                  The _4399 agent: intended use, evaluation with intervals, known weaknesses
                </span>
                <span className="text-muted-foreground mt-auto flex items-center gap-1 pt-3 text-xs">
                  Read <ArrowRight className="size-3" />
                </span>
              </Link>
            </li>
          </ul>
        </Section>

        <Section id="ai-use" eyebrow="Transparency" title="AI use statement">
          <Markdown nested source={withoutTitle(readDoc("ai-use-statement.md"))} />
          <p className="mt-6 text-sm">
            <Link href="/ai-log" className="underline underline-offset-4">
              Open the AI audit log
            </Link>{" "}
            to see every call made from this browser.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="bg-background/50 rounded-2xl border p-4">
      <h3 className="font-semibold">{title}</h3>
      <div className="text-muted-foreground mt-2 text-sm leading-relaxed">{children}</div>
    </div>
  );
}
