import { Download } from "lucide-react";
import type { Metadata } from "next";

import { AstarLab } from "@/components/astar/astar-lab";
import { HeuristicStudy } from "@/components/astar/heuristic-study";
import { PairedStudySummaryView } from "@/components/astar/paired-study-summary";
import { Finding, Section } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { summarisePairedStudy } from "@/lib/analysis/astar-paired";
import { loadAstarStudy } from "@/lib/data/load";
import { ASTAR_STUDY_CONFIG } from "@/lib/data/reference-config";
import { formatNumber, formatPStatement, formatPct } from "@/lib/stats/format";

export const metadata: Metadata = {
  title: "A* Lab",
  description:
    "Edit a Cachex board, run the original Part A A* search step by step, and compare Manhattan and Euclidean heuristics in a paired study with intervals and an optimality check.",
};

export default function AstarPage() {
  const { rows, meta } = loadAstarStudy();
  const summary = summarisePairedStudy(rows, { seed: ASTAR_STUDY_CONFIG.seed });
  const e = summary.expansions;
  const o = summary.optimality;
  const cfg = ASTAR_STUDY_CONFIG;
  // Phrase the paired mean difference as "fewer"/"more" rather than a negative count.
  const fewer = e.meanDiff.estimate < 0;
  const size = (x: number) => formatNumber(Math.abs(x), 1);
  const [near, far] = fewer
    ? [e.meanDiff.upper, e.meanDiff.lower]
    : [e.meanDiff.lower, e.meanDiff.upper];
  const pp = (x: number) => formatNumber(Math.abs(x) * 100, 1);
  const d = o.difference;
  const [dNear, dFar] = d.estimate < 0 ? [d.upper, d.lower] : [d.lower, d.upper];
  return (
    <div className="table-felt">
      <div className="mx-auto max-w-7xl space-y-10 px-4 py-6 sm:px-6 lg:py-10">
        <AstarLab />
        <Section
          id="paired-study"
          eyebrow="Reference study"
          title={`${summary.boards} paired boards: fewer expansions, at a price`}
          intro={
            <p>
              {cfg.boardsPerDimension} random boards for every size from {cfg.dimensions[0]} ×{" "}
              {cfg.dimensions[0]} to {cfg.dimensions.at(-1)} × {cfg.dimensions.at(-1)} from the
              notebook&apos;s generator (seed {cfg.seed}), each searched with both heuristics and
              solved by breadth-first search. Generated by{" "}
              <code className="font-mono text-sm">{meta.generatedBy}</code> with the A* port that
              reproduces the original paths and node counts exactly.
            </p>
          }
        >
          <ul className="mb-6 grid gap-3 md:grid-cols-3">
            <Finding>
              <strong>The report&apos;s direction holds, and is now measured.</strong> Manhattan
              expanded {size(e.meanDiff.estimate)} {fewer ? "fewer" : "more"} nodes per board on
              average (paired 95% CI {size(near)} to {size(far)} {fewer ? "fewer" : "more"}); fewer
              on {e.manhattanFewer} boards, more on {e.euclideanFewer}.
            </Finding>
            <Finding>
              <strong>But it finds a shortest path less often.</strong> Manhattan returned an
              optimal path on {formatPct(o.manhattan.p)} of solvable boards, Euclidean on{" "}
              {formatPct(o.euclidean.p)}: {pp(o.difference.estimate)} points{" "}
              {o.difference.estimate < 0 ? "fewer" : "more"} for Manhattan on the same boards
              (paired 95% CI {pp(dNear)} to {pp(dFar)}). Where only one heuristic was optimal, it
              was Manhattan on {o.mcnemar.b} boards and Euclidean on {o.mcnemar.c} (exact McNemar{" "}
              {formatPStatement(o.mcnemar.pValue)}).
            </Finding>
            <Finding>
              <strong>Why: neither heuristic is admissible here.</strong> Our 2022 report argued
              that both were; that was wrong. On this hex grid a step like (1, −1) costs 1, but
              Manhattan scores it 2 and Euclidean √2. Overestimating makes the search greedier:
              fewer expansions, longer paths. The two sample inputs happen to be solved optimally (8
              and 13 cells, confirmed by BFS).
            </Finding>
          </ul>
          <PairedStudySummaryView summary={summary} />
          <div className="mt-6">
            <Button asChild variant="outline" size="sm">
              <a href="/data/astar-paired-study.csv" download>
                <Download /> All {summary.boards} boards (CSV)
              </a>
            </Button>
          </div>
        </Section>
        <HeuristicStudy />
      </div>
    </div>
  );
}
