import { Download } from "lucide-react";
import type { Metadata } from "next";

import { AstarLab } from "@/components/astar/astar-lab";
import { HeuristicStudy } from "@/components/astar/heuristic-study";
import { PairedStudySummaryView } from "@/components/astar/paired-study-summary";
import { Finding, Section } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { summarisePairedStudy } from "@/lib/analysis/astar-paired";
import { loadAstarStudy } from "@/lib/data/load";
import { ASTAR_STUDY_CONFIG } from "@/lib/data/reference-config";
import { formatPct, formatSigned } from "@/lib/stats/format";

export const metadata: Metadata = {
  title: "A* Lab",
  description:
    "Edit a Cachex board, run the original Part A A* search step by step, and compare Manhattan and Euclidean heuristics in a paired study with intervals and an optimality check.",
};

export default function AstarPage() {
  const { rows, meta } = loadAstarStudy();
  const summary = summarisePairedStudy(rows, { seed: ASTAR_STUDY_CONFIG.seed });
  const e = summary.expansions;
  const o = summary.optimality;
  const cfg = ASTAR_STUDY_CONFIG;
  return (
    <div className="table-felt">
      <div className="mx-auto max-w-7xl space-y-10 px-4 py-6 sm:px-6 lg:py-10">
        <AstarLab />
        <Section
          id="paired-study"
          eyebrow="Reference study"
          title={`${summary.boards} paired boards: fewer expansions, at a price`}
          intro={
            <p>
              {cfg.boardsPerDimension} random boards for every size from {cfg.dimensions[0]} ×{" "}
              {cfg.dimensions[0]} to {cfg.dimensions.at(-1)} × {cfg.dimensions.at(-1)} from the
              notebook&apos;s generator (seed {cfg.seed}), each searched with both heuristics and
              solved by breadth-first search. Generated by{" "}
              <code className="font-mono text-sm">{meta.generatedBy}</code> with the A* port that
              reproduces the original paths and node counts exactly.
            </p>
          }
        >
          <ul className="mb-6 grid gap-3 md:grid-cols-3">
            <Finding>
              <strong>The report&apos;s direction holds, and is now measured.</strong> Manhattan
              expanded {formatSigned(e.meanDiff.estimate)} nodes per board on average (95% CI{" "}
              {formatSigned(e.meanDiff.lower)} to {formatSigned(e.meanDiff.upper)}); fewer on{" "}
              {e.manhattanFewer} boards, more on {e.euclideanFewer}.
            </Finding>
            <Finding>
              <strong>But it finds a shortest path less often.</strong> Manhattan returned an
              optimal path on {formatPct(o.manhattan.p)} of solvable boards (95% CI{" "}
              {formatPct(o.manhattan.lower)} to {formatPct(o.manhattan.upper)}), Euclidean on{" "}
              {formatPct(o.euclidean.p)} ({formatPct(o.euclidean.lower)} to{" "}
              {formatPct(o.euclidean.upper)}).
            </Finding>
            <Finding>
              <strong>Why: neither heuristic is admissible here.</strong> On this hex grid a step
              like (1, −1) costs 1, but Manhattan scores it 2 and Euclidean √2. Overestimating makes
              the search greedier: fewer expansions, longer paths. The two sample inputs happen to
              be solved optimally (8 and 13 cells, confirmed by BFS).
            </Finding>
          </ul>
          <PairedStudySummaryView summary={summary} />
          <div className="mt-6">
            <Button asChild variant="outline" size="sm">
              <a href="/data/astar-paired-study.csv" download>
                <Download /> All {summary.boards} boards (CSV)
              </a>
            </Button>
          </div>
        </Section>
        <HeuristicStudy />
      </div>
    </div>
  );
}
